<div class="max-w-7xl mx-auto px-4">
  <div class="flex flex-wrap -mx-2">
    <div class="w-full md:w-1/2">
      <form id="form1" method="POST">
        <input type="hidden" name="id" value="<?php echo $this->categoria->getId() ?>">
        <label class="etiquetas">Categoria</label><input readonly type="text" name='nombre' id='nombre' class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400" value="<?php echo $this->categoria->getNombre() ?>">
        <label id="nombre" style="display: inline-block;"></label><br>
        <label class="etiquetas">Importe</label><input type="text" name='importe' id='importe' class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400" value="<?php echo $this->categoria->getImporte() ?>"><br>
        <input class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded" type="submit" value="Guardar" />

      </form>
      <div id="resultado"></div>
    </div>
  </div>

</div>

<script>
  const form = document.getElementById('form1');

  form.addEventListener('submit', (e) => {
    e.preventDefault();
    const formData = new FormData(form);
    fetch('/movimientos/guardarCategoria', {
        method: 'POST',
        body: formData
      })
      .then(response => response.text())
      .then(data => {
        document.getElementById('resultado').innerHTML = "Categoría actualizada con éxito";
      })
      .catch(error => {
        document.getElementById('resultado').innerHTML = "Error al actualizar la categoría";
      });
  })
</script>
