<div class="container">
  <div class="row">
    <div class="col-md-6">
      <form id="form1" method="POST">
        <input type="hidden" name="id" value="<?php echo $this->categoria->getId() ?>">
        <label class="etiquetas">Categoria</label><input readonly type="text" name='nombre' id='nombre' class="form-control" value="<?php echo $this->categoria->getNombre() ?>">
        <label id="nombre" style="display: inline-block;"></label><br>
        <label class="etiquetas">Importe</label><input type="text" name='importe' id='importe' class="form-control" value="<?php echo $this->categoria->getImporte() ?>"><br>
        <input class="btn btn-success" type="submit" value="Guardar" />

      </form>
      <div id="resultado"></div>
    </div>
  </div>

</div>

<script>
  const form = document.getElementById('form1');

  form.addEventListener('submit', (e) => {
    e.preventDefault();
    const formData = new FormData(form);
    fetch('/movimientos/guardarCategoria', {
        method: 'POST',
        body: formData
      })
      .then(response => response.text())
      .then(data => {
        document.getElementById('resultado').innerHTML = "Categoría actualizada con éxito";
      })
      .catch(error => {
        document.getElementById('resultado').innerHTML = "Error al actualizar la categoría";
      });
  })
</script>