<p>&nbsp;</p>
<div class="container">
    <h3>Ingrese mes y a&ntilde;o a imprimir</h3>
    <div id="divpago">
        <form id="frmchoose"  class="form-horizontal" sytle="position: relative;">
            <div class="row">

                <div class="form-group">
                    <div class="col-md-1">
                        <label class="control-label">Socio</label>
                    </div>
                    <div class="col-md-2">
                        <input type="text" name='socio' id='socio' class="form-control" style="display: inline-block !important;">
                        <strong><span id="nombre">Name</span></strong>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-md-1">
                        <label class="control-label">Mes</label>
                    </div>
                    <div class="col-md-2">
                        <input type="text" name='mes' id='mes' class="form-control">
                    </div>
                </div>
    
                <div class="form-group">
                    <div class="col-md-1">
                        <label class="control-label col-md-1">A&ntilde;o</label>
                    </div>
                    <div class="col-md-2">
                        <input type="text" name='anio' id='anio' class="form-control">
                        
                    </div>
                </div>
                <div class="col-md-2">
                    <button id="agregar" class="form-control">Agregar</button>
                </div>
                <div class="col-md-2">
                    <input id="imprimir" type="button" value="Imprimir" class="btn btn-primary"/>
                </div>
    
            </div>

        </form>
        <div>
            <table class="table table-bordered table-striped" id="items">
                <tr>
                    <th>Nro</th>
                    <th>Nombre</th>
                    <th>Mes</th>
                    <th>Año</th>
                </tr>
            </table>
        </div>
    </div>
</div>
<script>
    const $agregar = document.querySelector("#agregar")
    const $frm = document.querySelector("#frmchoose")
    const $items = document.querySelector("#items")
    const $nombre = document.querySelector("#nombre")
    const $socio = document.querySelector("#socio")
    const $print = document.querySelector("#imprimir")
    $socio.addEventListener('change', async evt => {
        const formData = new FormData
        formData.append('id', $socio.value)
        let res = await fetch('/socios/loadSocioAjax', {
            method: 'post',
            body: formData
        })
        let response = await res.json()
        $nombre.innerHTML = response.nombre
    })
    $agregar.addEventListener('click', evt => {
        evt.preventDefault()
        const tr = document.createElement('tr')
        tr.setAttribute("class", "filas")
        let texto = `<td>${$frm.socio.value}</td>
                    <td>${document.querySelector("#nombre").innerHTML}</td>
                    <td>${$frm.mes.value}</td><td>${$frm.anio.value}</td>
        `
        tr.innerHTML = texto
        $items.children[0].appendChild(tr)
        //document.querySelector("#nombre").innerHTML = ""
        $frm.socio.value = ""
        $frm.mes.value = ""
        $frm.anio.value = ""
        $frm.socio.focus()
        
    })

    $print.addEventListener('click', evt => {
        evt.preventDefault()
        let lista = document.querySelectorAll(".filas")
        let listPrint = [...lista]
        listFinal = listPrint.map( l => {
            return {id: l.children[0].innerHTML, mes: l.children[2].innerHTML, anio: l.children[3].innerHTML}
        })
        console.log(listFinal)
    })
</script>