<div class="max-w-7xl mx-auto px-4">
    <span>Seguro que quiere generar el mes de <?php echo $this->mes ?>/<?php echo $this->anio ?></span>
    <p><a class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" href="<?php echo BASE_URL. 'movimientos/confirmar/'.$this->mes.'/'.$this->anio ?>">S&iacute;</a>
        <a href="<?php echo BASE_URL. 'movimientos/generar'?>" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">No</a></p>
</div>
