<div class="max-w-7xl mx-auto px-4">
    <h2>Listado de categorías</h2>
    <article id="formularios" class="w-full">
        <table class="table table-bordered table-condensed table-striped overflow-x-auto w-full">
            <tr>
                <th>Nro.</th>
                <th>Categoría</th>
                <th>Valor</th>
                <th></th>
            </tr>
            <?php foreach ($this->categorias as $p): ?>


                <tr>

                    <td><?php echo $p->getId(); ?></td>
                    <td><?php echo $p->getNombre(); ?></td>
                    <td><?php echo $p->getImporte() ?></td>
                    <td><a href="<?php echo BASE_URL . 'movimientos/editarCategoria/' . $p->getId(); ?>"><img src="<?php echo BASE_URL . 'views/layout/' . DEFAULT_LAYOUT . '/img/edit.png' ?>"></a></td>

                </tr>


            <?php endforeach; ?>
        </table>
    </article>
</div>
<br>

<br><br>
