<div class="max-w-7xl mx-auto px-4">
    <h2>Recibos pasados del <?php echo $this->fecha ?></h2>
    <article id="formularios" class="w-full">
        <table class="table table-bordered table-condensed table-striped overflow-x-auto w-full">
            <tr>
                <th>Nro.</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Importe</th>
                <th></th>
            </tr>
            <?php foreach ($this->pagos as $p): ?>


                <tr>

                    <td><?php echo $p->socio->getId(); ?></td>
                    <td><?php echo $p->socio->getNombre(); ?></td>
                    <td><?php echo $p->socio->getApellido(); ?></td>
                    <td><?php echo $p->importe ?></td>
                    <td><a href="<?php echo BASE_URL . 'movimientos/eliminarPago/' . $p->id_cuota . "/" . $this->fechaMy; ?>"><img src="<?php echo BASE_URL . 'views/layout/' . DEFAULT_LAYOUT . '/img/delete.png' ?>"></a></td>

                </tr>


            <?php endforeach; ?>
            <?php echo count($this->pagos) != 0 ? "<tr><td colspan='5'>Total de pagos: " . count($this->pagos) . "</td></tr>" : "No hay pagos";
            ?>
        </table>
    </article>
</div>
<br>

<br><br>
