<div class="container">
<br>
  <div class="row">
    <div class="col-md-6">
      <form id="form1">
        <label class="etiquetas">Nro de Socio</label><input type="text" name='id' id='id' class="form-control"><label id="nombre" style="display: inline-block;"></label><br>
        <label class="etiquetas">Desde</label><input type="date" name='desde' id='desde' class="form-control"><br>
        <label class="etiquetas">Hasta</label><input type="date" name='hasta' id='hasta' class="form-control"><br>
        <input type="submit" value="Guardar" />

      </form>

    </div>
    <div id="resultado"></div>
  </div>

</div>

<script>
  let form = document.getElementById('form1')
  let nombre = document.getElementById('nombre')
  let ids = document.getElementById('id')
  const $div = document.querySelector('#resultado')
  ids.addEventListener('change', async (evt) => {
    let formData = new FormData()
    formData.append('id', ids.value)
    let respuesta = await fetch(`/socios/loadSocioAjax`, {
      method: 'post',
      body: formData
    })
    let res = await respuesta.json()
    nombre.innerHTML = res.nombre
  })
  
  
  form.addEventListener('submit', async evt => {
    evt.preventDefault();
    if(form.desde.value < '1970-01-01' || form.hasta.value < '1970-01-01') {
      alert("El año debe tener 4 dígitos, por favor revise");
      return;
    }
    let formData = new FormData(form)
    let res = await fetch('/movimientos/ingresarAdelanto', {
      method: 'post',
      body: formData
    })
    let resp = await res.json()
    $div.innerHTML = resp.texto
    form.id.value = ""
    form.desde.value = ""
    form.hasta.value = ""
    form.id.focus();
  })

</script>
