<p>&nbsp;</p>
<div id="divpago" class="container">
    <form id="form_pago" class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2">Fecha</label>
            <div class="col-md-2">

                <input type="date" name='fecha' id='fecha' class="form-control">
                 
            </div>
            <div class="col-md-2"><a id="enlace" href="<?php echo BASE_URL. 'movimientos/getLasts/'?>" class="btn btn-info" style="pointer-events: none;">Pagos de la fecha</a></div>
        </div>
       
        <div class="form-group">

            <label class="control-label col-md-2">Nro de Socio</label>
            <div class="col-md-1">
                <input type="text" name='id' id='id' class="form-control">
            </div>
            <label id="nombre" name="nombre" class="control-label col-md-4">Name</label>


        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Importe</label>
            <div class="col-md-2">

                <input type="text" name='importe' id='importe' class="form-control">
            </div>
        </div>

        <input type="button" value="Guardar" class="btn btn-primary"/>

    </form>
    <div id="ultimos" style ="width: 100%; display: inline;" ></div>
</div>
<script>
    
    $enlace = document.querySelector("#enlace")
    $date = document.querySelector("#fecha")
    
    $date.addEventListener('change', evt => {
       if(evt.target.value) {
           $enlace.style.pointerEvents = 'auto'
       }
    })
    
    $enlace.addEventListener('click', evt => {
        evt.preventDefault();
        const frm = document.querySelector("#form_pago");
        let url = $enlace.href;
        url+= frm.fecha.value;
        window.location.href = url
        
    })
    

    $('#id').change(function() {
        $.post('/socios/loadSocioAjax', `id=${$(this).val()}`, function(resp) {
            $('#nombre').html(resp.nombre)
        }, 'json')
    })
    $('#form_pago').delegate('#id','keypress', function(e) {
        if(e.keyCode == 13) {
            $('#importe').focus();
        }
    })

    $('#form_pago').delegate('#importe','keypress', function(e) {
        if(e.keyCode == 13) {
            obj = $('#id');
            if($date.value < '1970-01-01') {
                alert("El año debe ser de 4 dígitos, por favor revise")
                return;
            }
                const data = 'id='+obj.val()+'&importe='+$('#importe').val()+'&fecha='+$('#fecha').val();
                $.post('/movimientos/ingresarPago/P', data, function(resp) {

                var contenido = '<p>&nbsp;</p><table class="table table-bordered table-condensed table-striped">'
                contenido += '<tr><th>Id</th><th>Nombre</th><th>Importe</th></tr>'
                for(var i = 0; i < resp.length; i++) {
                    contenido+= '<tr>'

                    contenido += '<td>'+ resp[i].id+'</td><td>'+resp[i].nombre+'</td><td>'+resp[i].importe+'</td></tr>'
                }
                contenido += '</table>'
                $("#ultimos").html('<p></p>');
                $("#ultimos").append(contenido);
            }, 'json')
            
            obj.val('');
            obj.focus();
        }
    })


</script>
