<p>&nbsp;</p>
<div id="divpago" class="max-w-7xl mx-auto px-4">
    <h3 class="etiquetas">Cambio de constraseña</h3>
    <form id="form_password" class="space-y-4">
        <?php echo csrf_field(); ?>
        <div class="mb-4">

            <label class="font-semibold">Password actual</label>
            <div class="w-full md:w-1/3">

                <input data-hash="<?php echo Session::get('usuario')->password ?>" type="password" data-id = "<?php echo Session::get('usuario')->idusuario ?>" name='actual' id='actual' class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400">
            </div>
        </div>
        <div class="mb-4">
            <label class="font-semibold">Nueva contraseña</label>
            <div class="w-full md:w-1/3">
                <input type="password" name='nuevo' id='nuevo' class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400">

            </div>

        </div>
        <div class="mb-4">
            <label class="font-semibold">Repita contraseña</label>
            <div class="w-full md:w-1/3">
                <input type="password" name='repetir' id='repetir' class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400">

            </div>

        </div>

        <input type="submit" value="Cambiar" class="bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"/>

    </form>

    <div id="mensaje" style="color: red; font-weight: bold; font-size: 2em; text-align:center; margin: 10px;">

    </div>

</div>

<script>
  let form = document.getElementById('form_password')
  let mensaje = document.getElementById('mensaje')
  form.addEventListener('submit', async evt => {
    evt.preventDefault()
    if(md5(form.actual.value) != form.actual.dataset.hash) {
      // console.log(form.actual.dataset.hash)
      // console.log(form.actual.value)
      mensaje.innerHTML = 'Password actual incorrecta'
      return
    }

    if(form.nuevo.value != form.repetir.value) {
      mensaje.innerHTML = 'No coincide el nuevo password con la verificación, revise'
      return
    }
    formData = new FormData()
    formData.append('id', form.actual.dataset.id)
    formData.append('password', form.nuevo.value)
    mensaje.style.color = 'green'
    let respuesta = await fetch('/usuarios/change', {
      method: 'post',
      body: formData
    })
    let res = await respuesta.text()
    mensaje.innerHTML = res
    form.actual.value = ''
    form.nuevo.value=''
    form.repetir.value=''
  })
</script>
