<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>Club Deportivo y Social El Fogón</title>
  <style lang="css">

    .contenedor {
      border: solid 1px red;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      width: 100%;
    }

    .contenedor input {
      min-width: 300px;
    }


  </style>
</head>
<body>
  <div class="contenedor">
    <div>
      <form action="login/loguear" method="POST">
        <?php echo csrf_field(); ?>
        <div class="mb-4">
            <label for="nombre">Usuario</label>
          <input type="text" class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400"  name="username">
        </div>

       <div class="mb-4">
         <label for="clave">Password</label>
          <input type="password" class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400" name="password">
       </div>

    <input class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" type="submit" value="Ingresar">
  </form>
    </div>

  </div>

</body>
</html>
