<div class="max-w-7xl mx-auto px-4">
<h3>Seguro que desea activar a <?php echo $this->socio; ?>?</h3>
<a class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded" href="<?php echo BASE_URL .'socios/activarf/'.$this->socio->getId(); ?>">S&iacute;</a>&nbsp;<a class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded" href="<?php echo BASE_URL .'socios/eliminados/'; ?>">No</a><br><br>
</div>
