<div class="max-w-7xl mx-auto px-4">
  <h2>Listado de socios eliminados en la última emisión</h2>
  <article id="formularios" class="w-full">
    <div class="flex flex-wrap -mx-2">

      <br>
      <div class="flex flex-wrap -mx-2">
        <div class="w-full">
          <table id="tabla" class="table table-striped table-condensed table-bordered w-full">
            <tr>
              <th>Nro.</th>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Activar</th>
              <th>Editar</th>
            </tr>
            <?php foreach ($this->socios as $soc): ?>

              <tr>
                <td><?php echo $soc->getId(); ?></td>
                <td><?php echo $soc->getNombre(); ?></td>
                <td><?php echo $soc->getApellido(); ?></td>
                <td><a href="<?php echo BASE_URL . 'socios/activar/' . $soc->getId(); ?>"><img src="<?php echo BASE_URL . 'views/layout/' . DEFAULT_LAYOUT . '/img/active.png' ?>"></a></td>
                <td><a href="<?php echo BASE_URL . 'socios/editar/' . $soc->getId(); ?>"><img src="<?php echo BASE_URL . 'views/layout/' . DEFAULT_LAYOUT . '/img/edit.png' ?>"></a></td>
              </tr>


            <?php endforeach; ?>
          </table>
        </div>
      </div>
  </article>
</div>

<br><br>