<div class="max-w-7xl mx-auto px-4">
  <br>
    <div id="mensaje"></div>
    <form id="form1" class="space-y-4">
      <div class="mb-4">
        <label class="font-semibold">Nro de documento</label>
        <div class="w-full md:w-1/4">
          <input type="text" name='search' id='search' onkeypress="return soloNumeros(event);" class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400">
        </div>
      </div>
      

      <input type="submit" value="Buscar" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded" >
  </form>
</div>
<br><br>
<div class="max-w-7xl mx-auto px-4" id="resultado"></div>

<script type="text/javascript">
 
 const frm = document.getElementById('form1')

 frm.addEventListener('submit', async (evt) => {
   evt.preventDefault()
   let formData = new FormData(frm)
   let res = await fetch('/socios/getByDoc', {
     method: 'post',
     body: formData
     
    })
    let resultado = await res.json()
    console.log(resultado)
    let html = `<table class="table w-full"> 
     <tr>
       <th>Nro Socio</th>
       <th>Nombre</th>
       <th>Documento</th>
       <th>Acciones</th>
     </tr>
     <tr>
       <td>${resultado.id}</td>
       <td>${resultado.nombre}</td>
       <td>${resultado.documento}</td>
       <td>
         <a href="/socios/editar/${resultado.id}" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">Editar</a>
         <a href="/socios/confirmar/${resultado.id}" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">Eliminar</a>
       </td>
       </tr>
       </table>`
     document.getElementById('resultado').innerHTML = html
  )


function soloNumeros(e)
{

  key = e.keyCode || e.which
  let numeros = "0123456789"
  let teclado = String.fromCharCode(key)
  let especiales = [8,9,37,39,46]
  if(teclado == '.') {
    return false
  }
  let teclado_especial = false
  for(let i in especiales) {

    if(key == especiales[i]) {
      teclado_especial = true
    }
  }

  if(numeros.indexOf(teclado) ==-1 && !teclado_especial) {
    return false
  }
}

</script>
