<div class="max-w-7xl mx-auto px-4">
  <div class="flex flex-wrap -mx-2">
    <div class="w-full md:w-1/2">
      <form id="form1" action="<?php echo BASE_URL . 'socios/guardarAdelanto/0' ?>" method="POST">
        <?php echo csrf_field(); ?>

        <label class="etiquetas">Nro de Socio</label><input type="text" name='id' id='id' class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400" value="<?php echo $this->adelanto['id_socio_fk'] ?>">
        <label id="nombre" style="display: inline-block;"></label><br>
        <label class="etiquetas">Desde</label><input type="date" name='nombre' id='desde' class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400" value="<?php echo $this->adelanto['desde'] ?>"><br>
        <label class="etiquetas">Hasta</label><input type="date" name='hasta' id='hasta' class="border border-gray-300 rounded px-3 py-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-400" value="<?php echo $this->adelanto['hasta'] ?>"><br>
        <input class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded" type="submit" value="Guardar" />

      </form>

    </div>
  </div>

</div>

<script>
  setTimeout( async () => {
    let form = document.getElementById('form1')
    let nombre = document.getElementById('nombre')
    let ids = document.getElementById('id')
    //
    // ids.addEventListener('change', async (evt) => {
      let formData = new FormData()
      formData.append('id', ids.value)
      let respuesta = await fetch(`/socios/loadSocioAjax`, {
        method: 'post',
        body: formData
      })
      let res = await respuesta.json()
      nombre.innerHTML = res.nombre
    // })

  }, 1500)
</script>
