<div class="max-w-7xl mx-auto px-4">
<h2>Listado de socios con cuotas adelantadas</h2>
<article id="formularios" class="w-full">

<br>
<div class="flex flex-wrap -mx-2">
  <div class="w-full md:w-2/3">
    <table id="tabla" class="table table-striped table-condensed table-bordered w-full">
      <tr>
          <th>Nro.</th><th>Nombre</th><th>Apellido</th><th>Desde</th><th>Hasta</th><th></th>
          <th></th>
      </tr>
      <?php $contador = 1; ?>
      <?php foreach($this->socios as $soc): ?>

       <tr>
           <td><?php echo $soc['id_socio_fk']; ?></td>
           <td><?php echo $soc['nombre']; ?></td>
           <td><?php echo $soc['apellido']; ?></td>
           <td><input type="date" value="<?php echo $soc['desde']; ?>" readonly style="border: none; background: transparent;"></td>
           <td><input type="date" value="<?php echo $soc['hasta']; ?>" readonly style="border: none; background: transparent;"></td>
           <td><a href="<?php echo BASE_URL . 'socios/editarAdelanto/' . $soc['id']; ?>"><img src="<?php echo BASE_URL . 'views/layout/' .DEFAULT_LAYOUT .'/img/edit.png' ?>"></a></td>
           <td><a href="<?php echo BASE_URL . 'socios/confirmarAdelanto/' . $soc['id_socio_fk']; ?>"><img src="<?php echo BASE_URL . 'views/layout/' .DEFAULT_LAYOUT .'/img/delete.png' ?>"></a></td>
               <?php $contador++; ?>
       </tr>


      <?php endforeach; ?>
    </table>
  </div>
</div>
    </article>
  </div>
<br>

<br><br>
