<br>
<div class="container">
  <form id="form1" action="<?php echo BASE_URL . 'socios/guardar/0'?>" method="POST" class="form-horizontal" enctype="multipart/form-data">
      <div class="form-group">
        <label class="control-label col-sm-2">Nro de Socio</label>
        <div class="col-sm-1">
          <input type="text" name='id' id='id' value="<?php echo $this->nroSocio ?>" readonly class="form-control">
        </div>
      </div>
      <input type="hidden" name="idsoc" id="idsoc" value=0>
      <div class="form-group">
        <label class="control-label col-sm-2">Nombre</label>
        <div class="col-sm-4">
          <input type="text" name='nombre' id='nombre'  class="form-control">
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">Apellido</label>
        <div class="col-sm-4">
          <input type="text" name='apellido' id='apellido'  class="form-control">
        </div>

      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">Documento</label>
        <div class="col-sm-4">
          <label for="check">Deshabilitar para extranjero</label>
          <input type="checkbox" name="check" id="check">
          <input type="text" onkeypress="return soloNumeros(event);" name='documento' id='documento'  class="form-control">
          <span id="alerta" style="color:red; font-weight:bold;"></span>
        </div>

      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">Domicilio</label>
        <div class="col-sm-4">
          <input type="text" name='domicilio' id='domicilio'  class="form-control">
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">Categor&iacute;a</label>
        <div class="col-sm-4">
          <select name="categorias" class="form-control">
          <?php foreach($this->categorias as $cat):?>

              <option id="<?php echo $cat->getId(); ?>" value="<?php echo $cat->getNombre()."_" . $cat->getId(); ?>">
                  <?php echo $cat->getNombre(); ?></option>
          <?php endforeach; ?>
          </select>
        </div>
      </div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-4">
              <div class="checkbox">
                  <label>
                      <input type="checkbox" name="exento" id="exento" value="ok"> Exento
                  </label>
              </div>
          </div>
      </div>
      <div class="form-group">
        <label for="foto" class="control-label col-sm-2">Foto</label>
        <div class="col-sm-4">
          <input type="file" name="foto" id="foto" class="form-control">
        </div>
        <img id="img-previa" src="<?php echo BASE_URL .'views/socios/img/socio.png' ?>" alt="Mi imagen" class="img-thumbnail" style="height:128px; width:96px;">
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">Fecha Ingreso</label>
        <div class="col-sm-3">
          <input type="text" name='fecha_ingreso' id='fecha_ingreso'   class="form-control">
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">Fecha Nacimiento</label>
        <div class="col-sm-3">
          <input type="text" name='fecha_nacimiento' id='fecha_nacimiento' class="form-control">
        </div>

      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">Tel&eacute;fono</label>
        <div class="col-sm-3">
          <input type="text" name='telefono' id='telefono'  class="form-control">
        </div>

      </div>
      <div class="form-group">
        <label class="control-label col-sm-2">E-mail</label>
        <div class="col-sm-3">
          <input type="text" name='email' id='email' class="form-control">
        </div>

      </div>
      <fieldset id="campos">
      <legend>Agregar Familiar</legend>
      <div class="form-group">
        <div class="col-sm-11">
          <div class="input-group">
            <div class="input-group-addon">
              <i class="fa fa-user" aria-hidden="true"></i>
            </div>
            <input type="text" class="form-control" id="name-parent" placeholder="Nombre">
            <div class="input-group-addon">
              <i class="fa fa-user" aria-hidden="true"></i>
            </div>
            <input type="text" class="form-control" id="apellido-parent" placeholder="Apellido">
            <div class="input-group-addon">
              <i class="fa fa-users" aria-hidden="true"></i>
            </div>
            <select type="text" class="form-control" id="parentezco" placeholder="Parentezco">
              <option value="c">Cónyuge</option>
              <option value="h">Hijo/a</option>
            </select>
            <div class="input-group-addon">
              <i class="fa fa-id-card" aria-hidden="true"></i>
            </div>
            <input type="text" class="form-control" id="document" placeholder="Documento">
            <div class="input-group-addon">
              <i class="fa fa-id-card" aria-hidden="true"></i>
            </div>
            <select type="text" class="form-control" id="sex" placeholder="Sexo">
              <option value="f">F</option>
              <option value="m">M</option>
            </select>
            <div class="input-group-addon">
              <i class="fa fa-mobile" aria-hidden="true"></i>
            </div>
            <input type="text" class="form-control" id="fecha" placeholder="Fecha N.">
          </div>
        </div>
        <div class="col-sm-1">
          <button type="button" id="add" class="btn"><i class="fa fa-plus-circle" aria-hidden="true"></i></button>
        </div>
      </div>
      <table id="respo" class="table table-condensed table-striped">
        <tr>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Parentezco</th>
          <th>Documento</th>
        </tr>
      </table>
      <button type="button" class="btn" id="remover"><i class="fa fa-minus-circle" aria-hidden="true"></i></button>
    </fieldset>
      <div class="parientes"></div>



      <input type="submit" value="Guardar" class="btn btn-success"/>

  </form>
</div>
<script type="text/javascript">
 const $parents = document.querySelector("parientes")
 let cuerpo = ``
 const frm = document.getElementById('form1')

 frm.addEventListener('submit', async (evt) => {
   evt.preventDefault()
   if(frm.apellido.value == '') {
     alert('Debe ingresar nombre y apellido por serparado')
     return
   }
   let formData = new FormData()
   formData.append('documento', frm.documento.value)
   let res = await fetch('/socios/getByDocumento', {
     method: 'post',
     body: formData
   })
   let resultado = await res.json()
   //console.log(resultado)
   if(resultado.documento != 0) {
     let alerta = document.getElementById('alerta')
     alerta.innerHTML = 'Socio existente en la base de datos, revise'
     frm.documento.focus()
     return
   }
   if(digitoCedula(frm.documento.value)) {
     frm.submit()
   } else {
     alert('Cédula erronea, verifique')
     frm.documento.focus()
   }
 })

function digitoCedula(ci) {
  if(document.getElementById('check').checked) {
    return true
  }
  let digitoIngresado = ci.substring(ci.length -1)
  let cedula = ci.substring(0, ci.length - 1)

  let arrayCedula = cedula.split('')
  if(arrayCedula.length < 6) {
    return false
  } else if (arrayCedula.length == 6) {
    arrayCedula.unshift(0)
  }
  let testigo = [2,9,8,7,6,3,4]
  let sumatoria = 0
  for(let i in testigo) {
    sumatoria+= testigo[i] * arrayCedula[i]
  }

  if((sumatoria % 10) == 0) {
    return 0 == digitoIngresado
  }
  else {
    return 10-(sumatoria % 10) == digitoIngresado
  }


}

function soloNumeros(e)
{

  key = e.keyCode || e.which
  let numeros = "0123456789"
  let teclado = String.fromCharCode(key)
  let especiales = [8,9,37,39,46]
  if(teclado == '.') {
    return false
  }
  let teclado_especial = false
  for(let i in especiales) {

    if(key == especiales[i]) {
      teclado_especial = true
    }
  }

  if(numeros.indexOf(teclado) ==-1 && !teclado_especial) {
    return false
  }
}

function mostrarImagen(input) {
 if (input.files && input.files[0]) {
  var reader = new FileReader();
  reader.onload = function (e) {
   $('#img-previa').attr('src', e.target.result);
  }
  reader.readAsDataURL(input.files[0]);
 }
}
 
$("#foto").change(function(){
 mostrarImagen(this);
});
</script>
