<div class="max-w-7xl mx-auto px-4">
  <?php use App\Core\Session; ?>
  <h2>Parientes</h2>
  <article id="formularios" class="w-full">
    <br><br>
    <div class="flex flex-wrap -mx-2">
      <a class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded" href="<?php echo BASE_URL . 'socios/nuevoPariente/' . $this->idSocio; ?>">Agregar Pariente</a>
    </div>
    <br><br>
    <div class="flex flex-wrap -mx-2">
      <div class="w-full md:w-2/3">
        <table id="tabla" class="table table-striped table-condensed table-bordered w-full">
          <tr>
            <th>Parentezco</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Documento</th>
            <th>Sexo</th>
            <th>F.Nac.</th>
            <th></th>
          </tr>
          <?php $contador = 1; ?>
          <?php foreach ($this->parientes as $soc): ?>

            <tr>
              <?php
              $parentezco = ($soc->getParentezco() == 'C') ? 'Cónyuge' : 'Hijo/a';
              ?>
              <td><?php echo $parentezco; ?></td>
              <td><?php echo $soc->getNombre(); ?></td>
              <td><?php echo $soc->getApellido(); ?></td>
              <td><?php echo $soc->getDocumento(); ?></td>
              <?php $sexo = 'F'; ?>
              <td><?php echo ($soc->getSexo() == 'F') ? 'Femenino' : 'Masculino'; ?></td>
              <td><?php echo date('d/m/Y',  strtotime($soc->getFechaNacimiento())); ?></td>
              <td><a href="<?php echo BASE_URL . 'socios/editarPariente/' . $soc->getId(); ?>"><img src="<?php echo BASE_URL . 'views/layout/' . DEFAULT_LAYOUT . '/img/edit.png' ?>"></a></td>
              <?php if (!Session::get('usuario')->perfil > 2): ?>
                <td><a href="<?php echo BASE_URL . 'socios/confirmar/' . $soc->getId(); ?>"><img src="<?php echo BASE_URL . 'views/layout/' . DEFAULT_LAYOUT . '/img/delete.png' ?>"></a></td>
              <?php endif ?>
              <?php $contador++; ?>
            </tr>
          <?php endforeach; ?>
        </table>
      </div>
    </div>
  </article>
</div>
<br><br>